# Specify a base image
FROM node:alpine

# Specify a working directory
WORKDIR '/app'

# Copy package.json from project to docker dir
COPY ./client/package.json .

RUN ls

# Install some dependencies
RUN npm install

# Copy everything else
COPY . .

# start app command
CMD ["npm", "run", "start"]