image: bcgdv/gitlab-ci-docker

stages:
  - test
  - build
  - deploy

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375

test:
  stage: test
  script:
    - pwd
    - ls
    - cd client
    - ls
    - cd..
    - docker build -t react-test -f ./client/Dockerfile.dev ./client
    - docker run react-test npm test -- --coverage

build:
  stage: build
  script:
    - docker build -t multi-client ./client
    - docker build -t multi-nginx ./nginx
    - docker build -t multi-server ./server
    - docker build -t multi-worker ./worker
    # Log in to docker CLI
    - echo $CI_REGISTRY_PASSWORD | docker login --username $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    # pushing images to docker hub
    - docker tag multi-client multi-client:$CI_BUILD_REF_NAME-$CI_PIPELINE_ID
    - docker tag multi-client multi-client:$CI_BUILD_REF_NAME-latest
    - docker tag multi-client multi-nginx:$CI_BUILD_REF_NAME-$CI_PIPELINE_ID
    - docker tag multi-client multi-nginx:$CI_BUILD_REF_NAME-latest
    - docker tag multi-client multi-server:$CI_BUILD_REF_NAME-$CI_PIPELINE_ID
    - docker tag multi-client multi-server:$CI_BUILD_REF_NAME-latest
    - docker tag multi-client multi-worker:$CI_BUILD_REF_NAME-$CI_PIPELINE_ID
    - docker tag multi-client multi-worker:$CI_BUILD_REF_NAME-latest
    - docker push multi-client
    - docker push multi-nginx
    - docker push multi-server
    - docker push multi-worker

deploy:
  stage: deploy
  script:
    - echo "deployment script"
  environment:
    name: development
  only:
    - master

